version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    container_name: image_grpc_service_db
    ports: 
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
  rabbitmqdata: